=== github-big-cheng/dev-framework/framework/framework-converter/converter-core/src/main/resources/META-INF/converter.dtd
<?xml version="1.0" encoding="utf-8" ?>

        <!ELEMENT trans (send, rcv) >
        <!ATTLIST trans
                name CDATA #REQUIRED
                desc CDATA #REQUIRED
                group CDATA #IMPLIED
                groupCode CDATA #IMPLIED>

        <!ELEMENT send (item|item-list|item-tree|item-map|item-json)* >
        <!ELEMENT rcv (item|item-list|item-tree|item-map|item-json)* >

        <!ELEMENT item EMPTY>
        <!ATTLIST item
                index CDATA #IMPLIED
                name CDATA #REQUIRED
                desc CDATA #REQUIRED
                type (String|Boolean|Integer|Long|Decimal|DecimalString|DateString|List|JsonString|Map|Tree|File|FileList) "String"
                notes CDATA #IMPLIED
                ignore-key (true|false) "false"
                paramType (path|query|header) "query"
                required (true|false) "false"
                default CDATA #IMPLIED
                mapper CDATA #IMPLIED
                target CDATA #IMPLIED
                fromPattern CDATA #IMPLIED
                toPattern CDATA #IMPLIED
                scale CDATA #IMPLIED
                thousandth (true|false) "false"
                lsub CDATA #IMPLIED
                rsub CDATA #IMPLIED
                lpad CDATA #IMPLIED
                rpad CDATA #IMPLIED
                padLen CDATA #IMPLIED
                maxlength CDATA #IMPLIED
                regular CDATA #IMPLIED
                regular-type (letter|number|mobile|url|email|idCard|postCode|longitude|latitude) #IMPLIED
                min CDATA #IMPLIED
                max CDATA #IMPLIED
                between CDATA #IMPLIED
                scope CDATA #IMPLIED>

        <!ELEMENT item-list (item|item-list|item-tree|item-map|item-json)*>
        <!ATTLIST item-list
                name CDATA #REQUIRED
                desc CDATA #REQUIRED
                notes CDATA #IMPLIED
                target CDATA #IMPLIED
                maxlength CDATA #IMPLIED
                required (true|false) "false"
                ignore-key (true|false) "false"
                put-all (true|false) "false"
                type (List) "List">

        <!ELEMENT item-map (item|item-list|item-tree|item-map|item-json)*>
        <!ATTLIST item-map
                name CDATA #REQUIRED
                desc CDATA #REQUIRED
                notes CDATA #IMPLIED
                type (Map) "Map"
                target CDATA #IMPLIED
                required (true|false) "false"
                ignore-key (true|false) "false"
                put-all (true|false) "false"
                random-key CDATA #IMPLIED>

        <!ELEMENT item-tree (item|item-list|item-tree|item-map|item-json)*>
        <!ATTLIST item-tree
                name CDATA #REQUIRED
                desc CDATA #REQUIRED
                notes CDATA #IMPLIED
                target CDATA #IMPLIED
                treeKey CDATA #REQUIRED
                ignore-key (true|false) "false"
                put-all (true|false) "false"
                type (Tree) "Tree"
                real-type (List|Map) #REQUIRED
                required (true|false) "false">

        <!ELEMENT item-json (item|item-list|item-tree|item-map|item-json)*>
        <!ATTLIST item-json
                name CDATA #REQUIRED
                desc CDATA #REQUIRED
                notes CDATA #IMPLIED
                target CDATA #IMPLIED
                type (JsonString) "JsonString"
                real-type (List|Map|Tree) #REQUIRED
                required (true|false) "false">

=== github-big-cheng/dev-framework/user_center/ucenter/ucenter_web/src/main/resources/converter/personOrg/list.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="personOrg/list" desc="部门/人员列表" group="部门调整" groupCode="personOrg">
    <send>
        <item name="pageNo" desc="页码" type="Integer" default="1"/>
        <item name="pageSize" desc="页容量" type="Integer" default="15"/>
        <item name="pathIds" desc="路径精确查询"/>
        <item name="deptIdQueryInWithChild" desc="部门Id(包括子级)" type="Integer"/>
        <item name="personIdQueryIn" desc="批量用户id,逗号分隔"/>
        <item name="personNameQueryLike" desc="人员姓名查询"/>
    </send>
    <rcv>
        <item name="total" type="Integer" desc="数据总量" default="0"/>
        <item-list name="list" desc="list">
            <item name="id" desc="id" type="Integer"/>
            <item name="rootOrgId" desc="机构id" type="Integer"/>
            <item name="orgId" desc="机构id" type="Integer" target="rootOrgId"/>
            <item name="orgName" desc="机构名称" mapper="ORG_HASH" target="rootOrgId"/>
            <item name="type" desc="类型" notes="1：人员机构中间表，0：人员部门中间表" type="Integer"/>
            <item name="deptId" desc="部门Id" type="Integer"/>
            <item name="deptName" desc="部门名称" target="deptId" mapper="ORG_HASH"/>
            <item name="personId" desc="人员Id" type="Integer"/>
            <item name="personName" desc="人员名称" target="personId" mapper="PERSON_HASH"/>
            <item name="posId" desc="职位ID" type="Integer"/>
            <item name="posName" desc="职位名称" target="posId" mapper="POS_HASH"/>
            <item name="isMain" desc="主机构" notes="1-是" type="Integer"/>
            <item name="isMainPerson" desc="主要负责人" notes="1:是  0:否" type="Integer"/>
            <item name="orderNo" desc="顺序号" type="Integer"/>
        </item-list>
    </rcv>
</trans>

=== github-big-cheng/dev-framework/user_center/ucenter/ucenter_web/src/main/resources/converter/menu/usertree.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="menu/usertree" desc="用户菜单" group="菜单管理" groupCode="menu">
    <send>
    </send>
    <rcv>
        <item-list name="list" desc="list" ignore-key="true">

            <item name="id" desc="id" type="Integer"/>
            <item name="name" desc="名称"/>
            <item name="code" desc="代码"/>
            <item name="orderNo" desc="顺序号" type="Integer"/>

            <!-- 菜单 -->
            <item-tree name="subFunction" desc="菜单列表" ignore-key="true" treeKey="subFunction" real-type="List">
                <item name="id" desc="id" />
                <item name="name" desc="菜单名称" />
                <item name="action" desc="请求地址" />
                <item name="code" desc="代码" />
                <item name="parentId" desc="父级菜单" type="Integer"/>
                <item name="projectId" desc="应用ID" type="Integer"/>
                <item name="imgPath" desc="图标路径" />
                <item name="orderNo" desc="排序号" type="Integer"/>
                <item name="type" desc="类型" notes="1-菜单 2-子菜单 3-tab页签 4-按钮" />
            </item-tree>
        </item-list>
    </rcv>
</trans>

=== github-big-cheng/dev-framework/user_center/sys/sys_web/src/main/resources/converter/project/view.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="project/view" desc="应用管理-查看" group="应用管理" groupCode="project" >
    <send>
        <item name="id" desc="id" required="true" />
    </send>
    <rcv>
        <item name="id" desc="id" type="Integer"/>
        <item name="name" desc="名称" />
        <item name="code" desc="代码" />
        <item name="orderNo" desc="顺序号" type="Integer"/>
        <item name="isTool" desc="是否是工具条" type="Integer"/>
        <item name="isSys" desc="子系统风格" type="Integer"
              notes="//0和3是ssh(app,wms,dss,pss,pams)框架的：0表示ssh框架的子系统是同一个浏览器打开，3表示ssh框架的子系统是新浏览器打开，
              //1和4表示ssm框架：1表示ssm框架的子系统是同一个浏览器打开，4表示ssm框架的子系统是新浏览器打开。
              // 2表示跟系统无关的一些网站，不需要登录的，例如门户网站、三维可视化、虚拟现实等" />
        <item name="isDefault" desc="默认选中"  type="Integer"/>
        <item name="outControl" desc="前台始终显示" notes="不收权限控制 1:不受控， 0：受控"  type="Integer"/>
        <item name="path" desc="路径"/>
        <item name="keyValue" desc="缓存中的key"/>
        <item name="isApp" desc="是否应用配置" type="Integer"/>
        <item name="dataBase" desc="数据库名"/>
        <item name="isLongRange" desc="是否远程控制" type="Integer"/>
        <item name="urlId" desc="地址参数"  type="Integer"/>
        <item name="urlSetId" desc="应用地址配置ID"  type="Integer"/>
    </rcv>
</trans>

=== github-big-cheng/dev-framework/user_center/ucenter/ucenter_web/src/main/resources/converter/org/deptperson.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="org/deptperson" desc="部门人员树" group="部门管理" groupCode="org">
    <send>
        <item name="compTypeQueryIn" desc="类型" notes="10027-10:部门, 10027-20:公司"/>

    </send>
    <rcv>
        <item-tree name="list" desc="list" ignore-key="true" treeKey="children" real-type="List">
            <item name="id" desc="id" type="Integer"/>
            <item name="code" desc="代码"/>
            <item name="cname" desc="名称"/>
            <item name="sname" desc="简称"/>
            <item name="pathIds" desc="路径" notes="ROOT_ID-10001-10002…"/>
            <item name="orderNo" desc="顺序号" type="Integer"/>
            <item name="parentId" desc="上级部门" type="Integer"/>
            <item name="parentValue" desc="上级部门名称" mapper="ORG_HASH" target="parentId"/>

            <!-- 人员信息 -->
            <item-list name="listPerson" desc="人员列表">
                <item name="id" desc="人员id" type="Integer"/>
                <item name="orgId" desc="机构id" type="Integer"/>
                <item name="orgName" desc="机构名称"/>
                <item name="deptId" desc="部门id" type="Integer"/>
                <item name="deptName" desc="部门名称" target="deptId" mapper="ORG_HASH"/>
                <item name="name" desc="姓名"/>
                <item name="posId" desc="职务" type="Integer"/>
                <item name="posName" desc="职务" target="posId" mapper="POS_HASH"/>
                <item name="posLevel" desc="职级"/>
                <item name="posLevelName" desc="职级" target="posLevel" mapper="CODE_HASH"/>
                <item name="orderNo" desc="顺序号" type="Integer"/>
            </item-list>

        </item-tree>
    </rcv>
</trans>

=== github-big-cheng/dev-framework/user_center/sys/sys_web/src/main/resources/converter/code/save.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="code/save" desc="系统代码-保存" group="代码管理" groupCode="code">
    <send>
        <item name="type" desc="类别" required="true"/>
        <item name="code" desc="代码" required="true"/>
        <item name="locale" desc="国际化" required="true" default="zh_CN"/>
        <item name="name" desc="名称" required="true"/>
        <item name="value" desc="代码值" required="true"/>
        <item name="pathValue" desc="PATH"/>
        <item name="sname" desc="简称"/>
        <item name="ename" desc="英文名称"/>
        <item name="orderNo" desc="排序字段" type="Integer"/>
        <item name="parent" desc="父级"/>
        <item name="isSys" desc="系统/用户" notes="1-系统 0-用户" scope="0,1" type="Integer" required="true"/>
    </send>
    <rcv>
        <item name="value" desc="代码值" ignore-key="true"/>
    </rcv>
</trans>

=== github-big-cheng/dev-framework/user_center/sys/sys_web/src/main/resources/converter/parameter/save.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="sysParameter/save" desc="保存" group="系统参数" groupCode="sysParameter">
    <send>
        <item name="idDelIn" desc="要删除ids"/>
        <item name="orgId" desc="机构ID" type="Integer" required="true"/>
        <item name="orgName" desc="机构名称"/>
        <item name="setType" desc="参数类型" scope="1,2,3" required="true"
              notes="系统设置参数类型 1-系统运行参数、2-管理属性、3-系统显示设置"/>
        <item-list name="parameters" desc="参数集合">
            <item name="id" desc="id" type="Integer" notes="修改时需上传"/>
            <item name="keies" desc="key" required="true"/>
            <item name="descript" desc="描述"/>
            <item name="value" desc="值" required="true"/>
            <item name="type" desc="类型"/>
            <item name="subType" desc="子类型"/>
            <item name="orderNo" desc="排序" type="Integer"/>
            <item name="remark" desc="备注"/>
        </item-list>
    </send>
    <rcv>
    </rcv>
</trans>

=== github-big-cheng/dev-framework/user_center/ucenter/ucenter_web/src/main/resources/converter/position/add.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="ucenterPosition/add" desc="职位管理-新增" group="职位管理" groupCode="ucenterPosition">
    <send>
        <item name="name" desc="名称" required="true"/>
        <item name="code" desc="代码" required="true"/>
        <item name="type" desc="职务类型"/>
        <item name="memo" desc="备注"/>
    </send>
    <rcv>
        <item name="id" desc="id" type="Integer" ignore-key="true"/>
    </rcv>
</trans>

=== github-big-cheng/dev-framework/user_center/sys/sys_web/src/main/resources/converter/function/view.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="function/view" desc="菜单管理-查看" group="菜单管理" groupCode="function">
    <send>
        <item name="id" desc="菜单ID" />
    </send>
    <rcv>
        <item name="name" desc="菜单名称"  />
        <item name="code" desc="代码" />
        <item name="action" desc="请求地址" />
        <item name="parentId" desc="父级菜单" type="Integer" />
        <item name="parentName" desc="父级菜单" />
        <item name="projectId" desc="应用ID" type="Integer"/>
        <item name="imgPath" desc="图标路径" />
        <item name="orderNo" desc="排序号" />
        <item name="type" type="Integer" desc="类型" notes="1-菜单 2-子菜单 3-tab页签 4-按钮"/>
    </rcv>
</trans>
