=== github-big-cheng/dev-framework/framework/framework-converter/converter-core/src/main/resources/META-INF/converter.dtd
<?xml version="1.0" encoding="utf-8" ?>

        <!ELEMENT trans (send, rcv) >
        <!ATTLIST trans
                name CDATA #REQUIRED
                desc CDATA #REQUIRED
                group CDATA #IMPLIED
                groupCode CDATA #IMPLIED>

        <!ELEMENT send (item|item-list|item-tree|item-map|item-json)* >
        <!ELEMENT rcv (item|item-list|item-tree|item-map|item-json)* >

        <!ELEMENT item EMPTY>
        <!ATTLIST item
                index CDATA #IMPLIED
                name CDATA #REQUIRED
                desc CDATA #REQUIRED
                type (String|Boolean|Integer|Long|Decimal|DecimalString|DateString|List|JsonString|Map|Tree|File|FileList) "String"
                notes CDATA #IMPLIED
                ignore-key (true|false) "false"
                paramType (path|query|header) "query"
                required (true|false) "false"
                default CDATA #IMPLIED
                mapper CDATA #IMPLIED
                target CDATA #IMPLIED
                fromPattern CDATA #IMPLIED
                toPattern CDATA #IMPLIED
                scale CDATA #IMPLIED
                thousandth (true|false) "false"
                lsub CDATA #IMPLIED
                rsub CDATA #IMPLIED
                lpad CDATA #IMPLIED
                rpad CDATA #IMPLIED
                padLen CDATA #IMPLIED
                maxlength CDATA #IMPLIED
                regular CDATA #IMPLIED
                regular-type (letter|number|mobile|url|email|idCard|postCode|longitude|latitude) #IMPLIED
                min CDATA #IMPLIED
                max CDATA #IMPLIED
                between CDATA #IMPLIED
                scope CDATA #IMPLIED>

        <!ELEMENT item-list (item|item-list|item-tree|item-map|item-json)*>
        <!ATTLIST item-list
                name CDATA #REQUIRED
                desc CDATA #REQUIRED
                notes CDATA #IMPLIED
                target CDATA #IMPLIED
                maxlength CDATA #IMPLIED
                required (true|false) "false"
                ignore-key (true|false) "false"
                put-all (true|false) "false"
                type (List) "List">

        <!ELEMENT item-map (item|item-list|item-tree|item-map|item-json)*>
        <!ATTLIST item-map
                name CDATA #REQUIRED
                desc CDATA #REQUIRED
                notes CDATA #IMPLIED
                type (Map) "Map"
                target CDATA #IMPLIED
                required (true|false) "false"
                ignore-key (true|false) "false"
                put-all (true|false) "false"
                random-key CDATA #IMPLIED>

        <!ELEMENT item-tree (item|item-list|item-tree|item-map|item-json)*>
        <!ATTLIST item-tree
                name CDATA #REQUIRED
                desc CDATA #REQUIRED
                notes CDATA #IMPLIED
                target CDATA #IMPLIED
                treeKey CDATA #REQUIRED
                ignore-key (true|false) "false"
                put-all (true|false) "false"
                type (Tree) "Tree"
                real-type (List|Map) #REQUIRED
                required (true|false) "false">

        <!ELEMENT item-json (item|item-list|item-tree|item-map|item-json)*>
        <!ATTLIST item-json
                name CDATA #REQUIRED
                desc CDATA #REQUIRED
                notes CDATA #IMPLIED
                target CDATA #IMPLIED
                type (JsonString) "JsonString"
                real-type (List|Map|Tree) #REQUIRED
                required (true|false) "false">

=== github-big-cheng/dev-framework/user_center/ucenter/ucenter_web/src/main/resources/converter/role/add.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="role/add" desc="角色管理-新增" group="角色管理" groupCode="role" >
    <send>
        <item name="name" desc="名称" required="true"/>
        <item name="code" desc="代码" required="true"/>
        <item name="memo" desc="备注"/>
        <item name="orderNo" desc="顺序号" type="Integer"/>
    </send>
    <rcv>
        <item name="id" desc="id" type="Integer" ignore-key="true"/>
    </rcv>
</trans>

=== github-big-cheng/dev-framework/user_center/ucenter/ucenter_web/src/main/resources/converter/personOrg/view.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="personOrg/view" desc="查看单个人员的人员部门信息" group="部门调整" groupCode="personOrg">
    <send>
        <item name="personId" desc="人员id" type="Integer" required="true"/>
    </send>
    <rcv>
        <item name="id" desc="id" type="Integer"/>
        <item name="type" desc="类型" notes="1：人员机构中间表，0：人员部门中间表" type="Integer"/>
        <item name="deptId" desc="部门Id" type="Integer"/>
        <item name="deptName" desc="部门名称" target="deptId" mapper="ORG_HASH"/>
        <item name="personId" desc="人员Id" type="Integer"/>
        <item name="personName" desc="人员名称" target="personId" mapper="PERSON_HASH"/>
        <item name="posId" desc="职位ID" type="Integer"/>
        <item name="posName" desc="职位名称" target="posId" mapper="POS_HASH"/>
        <item name="isMain" desc="主机构" notes="1-是" type="Integer"/>
        <item name="isMainPerson" desc="主要负责人" notes="1:是  0:否" type="Integer"/>
        <item name="orderNo" desc="顺序号" type="Integer"/>
    </rcv>
</trans>

=== github-big-cheng/dev-framework/user_center/sys/sys_web/src/main/resources/converter/code/list.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="code/list" desc="系统代码-列表" group="代码管理" groupCode="code">
    <send>
        <item name="pageNo" desc="页码" type="Integer" default="1"/>
        <item name="pageSize" desc="页容量" type="Integer" default="15"/>
        <item name="type" desc="类别(精确查询)"/>
        <item name="codeQueryLike" desc="代码模糊查询"/>
        <item name="nameQueryLike" desc="名称模糊查询"/>
        <item name="codeOrNameQueryLike" desc="代码或者名称查询"/>
        <item name="pathValueQueryLike" desc="pathValue模糊查询"/>
        <item name="typeQueryNotIn" desc="类型过滤"/>
    </send>

    <rcv>
        <item name="total" type="Integer" desc="数据总量" default="0"/>
        <item-list name="list" desc="list">
            <item name="id" desc="id" type="Integer"/>
            <item name="locale" desc="国际化"/>
            <item name="code" desc="代码"/>
            <item name="value" desc="代码值"/>
            <item name="pathValue" desc="PATH"/>
            <item name="name" desc="名称"/>
            <item name="orderNo" desc="排序字段" type="Integer"/>
            <item name="type" desc="类别"/>
            <item name="typeValue" desc="类别名称" mapper="CODE_HASH" target="type"/>
            <item name="parent" desc="父级"/>
            <item name="parentValue" desc="父级" mapper="CODE_HASH" target="parent"/>
            <item name="isSys" desc="系统/用户" notes="1-系统 0-用户" type="Integer"/>
        </item-list>
    </rcv>
</trans>

=== github-big-cheng/dev-framework/user_center/sys/sys_web/src/main/resources/converter/parameter/list.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="sysParameter/list" desc="列表" group="系统参数" groupCode="sysParameter">
    <send>
        <item name="orgId" desc="机构ID" required="true"/>
        <item name="setType" desc="类型" scope="1,2,3" notes="1-系统运行参数、2-管理属性、3-系统显示设置"/>
        <item name="keies" desc="KEY"/>
    </send>
    <rcv>
        <item name="total" type="Integer" desc="数量" default="0"/>
        <item-list name="list" desc="列表">
            <item name="id" desc="id" type="Integer" notes="修改时需上传"/>
            <item name="orgId" desc="机构ID" type="Integer"/>
            <item name="orgName" desc="机构(单位)"/>
            <item name="setType" desc="类型" type="Integer"/>
            <item name="keies" desc="key" />
            <item name="descript" desc="描述"/>
            <item name="value" desc="值" />
            <item name="outValue" desc="外网地址"/>
            <item name="dataBase" desc="数据库"/>
            <item name="customAttr" desc="自定义属性" notes="当disType为7的时候，自定义的单选按钮的名字需要放这里,如0:一对一;1:一对多"/>
            <item name="altValue" desc="备选项"/>
            <item name="disType" desc="显示方式" notes="1-文本输入框、2-下拉框、3-复选框、4-单选、5-附件图片"/>
            <item name="orderBy" desc="排序" type="Integer"/>
            <item name="remark" desc="备注"/>
        </item-list>
    </rcv>
</trans>

=== github-big-cheng/dev-framework/user_center/ucenter/ucenter_web/src/main/resources/converter/role/list.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="role/list" desc="角色管理-列表" group="角色管理" groupCode="role">
    <send>
        <item name="type" desc="列表区分" notes="人员管理列表传 type=person"/>
        <item name="nameQueryLike" desc="名称模糊查询"/>
        <item name="codeQueryLike" desc="代码模糊查询"/>
        <item name="codeOrNameLike" desc="模糊分页查询代码/名称关键字"/>
        <item name="pageNo" desc="页码" type="Integer" default="1"/>
        <item name="pageSize" desc="页容量" type="Integer" default="15"/>
    </send>
    <rcv>
        <item name="total" type="Integer" desc="数据总量" default="0"/>
        <item-list name="list" desc="list">
            <item name="id" desc="id" type="Integer"/>
            <item name="name" desc="名称"/>
            <item name="orgId" desc="机构ID 为系统后续多机构新增字段" type="Integer"/>
            <item name="orgName" desc="机构名称"/>
            <item name="code" desc="代码"/>
            <item name="memo" desc="描述"/>
            <item name="orderNo" desc="顺序号"/>
            <item name="isSys" desc="是否系统初始化" notes="0-否 1-是" type="Integer"/>
            <item name="createByName" desc="录入人姓名" mapper="USER_PERSON_NAME_HASH" target="createBy"/>
            <item name="createTime" desc="录入时间"/>
        </item-list>
    </rcv>
</trans>

=== github-big-cheng/dev-framework/user_center/sys/sys_web/src/main/resources/converter/function/add.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="function/add" desc="菜单管理-新增" group="菜单管理" groupCode="function" >
    <send>
        <item name="name" desc="菜单名称" required="true" />
        <item name="type" desc="类型" type="Integer" notes="1-菜单 2-子菜单 3-tab页签 4-按钮" scope="1,2,3,4" required="true" />
        <item name="action" desc="请求地址" />
        <item name="code" desc="代码" required="true"/>
        <item name="parentId" desc="父级菜单" type="Integer"/>
        <item name="projectId" desc="应用ID" type="Integer" required="true"/>
        <item name="imgPath" desc="图标路径" />
        <item name="orderNo" desc="排序号" type="Integer"/>
    </send>
    <rcv>
        <item name="id" desc="id" type="Integer"/>
    </rcv>
</trans>

=== github-big-cheng/dev-framework/user_center/ucenter/ucenter_web/src/main/resources/converter/org/tree.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="org/tree" desc="机构部门树" group="部门管理" groupCode="org">
    <send>
        <item name="isAll" desc="是否进行权限过滤 不为空就查询所有机构,为空就查询当前人所属机构的" type="Integer"/>
    </send>
    <rcv>
        <item-tree name="list" desc="list" ignore-key="true" treeKey="children" real-type="List">
            <item name="id" desc="id" type="Integer"/>
            <item name="code" desc="代码"/>
            <item name="cname" desc="名称"/>
            <item name="sname" desc="简称"/>
            <item name="pathIds" desc="路径" notes="ROOT_ID-10001-10002…"/>
            <item name="orderNo" desc="顺序号" type="Integer"/>
            <item name="parentId" desc="上级部门" type="Integer"/>
            <item name="parentValue" desc="上级部门名称" mapper="ORG_HASH" target="parentId"/>
        </item-tree>
    </rcv>
</trans>

=== github-big-cheng/dev-framework/user_center/ucenter/ucenter_web/src/main/resources/converter/position/edit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="ucenterPosition/edit" desc="职位管理-编辑" group="职位管理" groupCode="ucenterPosition">
    <send>
        <item name="id" desc="id" type="Integer" required="true"/>
        <item name="name" desc="名称" required="true"/>
        <item name="code" desc="代码" required="true"/>
        <item name="type" desc="职务类型"/>
        <item name="memo" desc="备注"/>
    </send>
    <rcv>
        <item name="id" desc="id" type="Integer" ignore-key="true"/>
    </rcv>
</trans>
