=== github-big-cheng/dev-framework/framework/framework-converter/converter-core/src/main/resources/META-INF/converter.dtd
<?xml version="1.0" encoding="utf-8" ?>

        <!ELEMENT trans (send, rcv) >
        <!ATTLIST trans
                name CDATA #REQUIRED
                desc CDATA #REQUIRED
                group CDATA #IMPLIED
                groupCode CDATA #IMPLIED>

        <!ELEMENT send (item|item-list|item-tree|item-map|item-json)* >
        <!ELEMENT rcv (item|item-list|item-tree|item-map|item-json)* >

        <!ELEMENT item EMPTY>
        <!ATTLIST item
                index CDATA #IMPLIED
                name CDATA #REQUIRED
                desc CDATA #REQUIRED
                type (String|Boolean|Integer|Long|Decimal|DecimalString|DateString|List|JsonString|Map|Tree|File|FileList) "String"
                notes CDATA #IMPLIED
                ignore-key (true|false) "false"
                paramType (path|query|header) "query"
                required (true|false) "false"
                default CDATA #IMPLIED
                mapper CDATA #IMPLIED
                target CDATA #IMPLIED
                fromPattern CDATA #IMPLIED
                toPattern CDATA #IMPLIED
                scale CDATA #IMPLIED
                thousandth (true|false) "false"
                lsub CDATA #IMPLIED
                rsub CDATA #IMPLIED
                lpad CDATA #IMPLIED
                rpad CDATA #IMPLIED
                padLen CDATA #IMPLIED
                maxlength CDATA #IMPLIED
                regular CDATA #IMPLIED
                regular-type (letter|number|mobile|url|email|idCard|postCode|longitude|latitude) #IMPLIED
                min CDATA #IMPLIED
                max CDATA #IMPLIED
                between CDATA #IMPLIED
                scope CDATA #IMPLIED>

        <!ELEMENT item-list (item|item-list|item-tree|item-map|item-json)*>
        <!ATTLIST item-list
                name CDATA #REQUIRED
                desc CDATA #REQUIRED
                notes CDATA #IMPLIED
                target CDATA #IMPLIED
                maxlength CDATA #IMPLIED
                required (true|false) "false"
                ignore-key (true|false) "false"
                put-all (true|false) "false"
                type (List) "List">

        <!ELEMENT item-map (item|item-list|item-tree|item-map|item-json)*>
        <!ATTLIST item-map
                name CDATA #REQUIRED
                desc CDATA #REQUIRED
                notes CDATA #IMPLIED
                type (Map) "Map"
                target CDATA #IMPLIED
                required (true|false) "false"
                ignore-key (true|false) "false"
                put-all (true|false) "false"
                random-key CDATA #IMPLIED>

        <!ELEMENT item-tree (item|item-list|item-tree|item-map|item-json)*>
        <!ATTLIST item-tree
                name CDATA #REQUIRED
                desc CDATA #REQUIRED
                notes CDATA #IMPLIED
                target CDATA #IMPLIED
                treeKey CDATA #REQUIRED
                ignore-key (true|false) "false"
                put-all (true|false) "false"
                type (Tree) "Tree"
                real-type (List|Map) #REQUIRED
                required (true|false) "false">

        <!ELEMENT item-json (item|item-list|item-tree|item-map|item-json)*>
        <!ATTLIST item-json
                name CDATA #REQUIRED
                desc CDATA #REQUIRED
                notes CDATA #IMPLIED
                target CDATA #IMPLIED
                type (JsonString) "JsonString"
                real-type (List|Map|Tree) #REQUIRED
                required (true|false) "false">

=== github-big-cheng/dev-framework/user_center/sys/sys_web/src/main/resources/converter/sysoperationlog/list.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="sysOperationLog/list" desc="列表" group="操作日志" groupCode="sysOperationLog">
    <send>
        <!--这里存放的是参数,之后补充完善-->
        <item name="pageNo" desc="页码" type="Integer" default="1"/>
        <item name="pageSize" desc="页容量" type="Integer" default="15"/>
        <item name="opTimeQueryGe" desc="开始时间"/>
        <item name="opTimeQueryLe" desc="结束时间"/>
    </send>
    <rcv>
        <item name="total" type="Integer" desc="id" default="0"/>
        <item-list name="list" desc="列表">
            <item name="id" desc="id" type="Integer"/>
            <item name="targetServer" desc="访问实例"/>
            <item name="requestPath" desc="请求路径"/>
            <item name="ip" desc="请求ip"/>
            <item name="requestMethod" desc="请求方法"/>
            <item name="schema" desc="协议"/>
            <item name="osType" desc="操作系统类型"/>
            <item name="token" desc="令牌"/>
            <item name="userId" desc="用户ID" type="Integer"/>
            <item name="userName" desc="用户名称" target="userId" mapper="USER_PERSON_NAME_HASH"/>
            <item name="requestBody" desc="请求体"/>
            <item name="responseData" desc="响应体"/>
            <item name="requestTime" desc="请求时间"/>
            <item name="responseTime" desc="响应时间"/>
            <item name="executeTime" desc="执行时间" type="Integer"/>
        </item-list>
    </rcv>
</trans>

=== github-big-cheng/dev-framework/user_center/ucenter/ucenter_web/src/main/resources/converter/position/view.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="ucenterPosition/view" desc="职位管理-查看" group="职位管理" groupCode="ucenterPosition">
    <send>
        <item name="id" desc="id" type="Integer" required="true"/>
    </send>
    <rcv>
        <item name="id" desc="id" type="Integer"/>
        <item name="orgId" desc="机构ID 为系统后续多机构新增字段" type="Integer"/>
        <item name="orgName" desc="机构名称"/>
        <item name="name" desc="名称"/>
        <item name="code" desc="代码"/>
        <item name="type" desc="类型"/>
        <item name="typeName" desc="类型名称" target="type" mapper="CODE_HASH"/>
        <item name="memo" desc="描述"/>
    </rcv>
</trans>

=== github-big-cheng/dev-framework/user_center/ucenter/ucenter_web/src/main/resources/converter/person/list.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="person/list" desc="人员信息-列表" groupCode="person" group="人员管理">
    <send>
        <item name="pageNo" desc="页码" default="1" type="Integer"/>
        <item name="pageSize" desc="每页大小" default="15" type="Integer"/>
        <item name="sex" desc="性别" notes="TYPE=10001-10004"/>
        <item name="marriage" desc="婚姻状况" notes="TYPE=10001-10005"/>
        <item name="education" desc="学历状况" notes="TYPE=10001-10006"/>
        <item name="roleIdQuery" desc="角色id精确查询" type="Integer"/>
        <item name="nameQueryLike" desc="姓名模糊查询"/>
        <item name="nameOrAccountQueryLike" desc="姓名或者账号模糊查询"/>
        <item name="pathIds" desc="路径精确查询"/>
    </send>
    <rcv>
        <item name="total" type="Integer" desc="数据总量" default="0"/>
        <item-list name="list" desc="多条人员数据">
            <!-- 基本信息 -->
            <item name="id" desc="人员id" type="Integer"/>
            <item name="orgId" desc="机构ID" type="Integer"/>
            <item name="orgName" desc="机构名称"/>
            <item name="name" desc="姓名"/>
            <item name="jobNo" desc="工号"/>
            <item name="idNo" desc="身份证号码"/>
            <item name="mobile" desc="手机"/>
            <item name="personState" desc="员工状态"/>

            <!-- 基本信息 -->
            <item name="sex" desc="性别 TYPE=10001-10004, 10004-10:男 10004-20:女 "/>
            <item name="sexName" desc="性别" mapper="CODE_HASH" target="sex"/>
            <item name="marriage" desc="婚姻状况 TYPE=10001-10005, 10005-10:已婚  10005-20:未婚 "/>
            <item name="marriageName" desc="婚姻状况" mapper="CODE_HASH" target="marriage"/>
            <item name="birthday" desc="出生日期"/>
            <item name="nation" desc="民族"/>
            <item name="nationName" desc="民族" target="nation" mapper="CODE_HASH"/>
            <item name="telephone" desc="电话"/>
            <item name="email" desc="email地址"/>
            <item name="memo" desc="备注"/>
            <item name="createTime" desc="创建时间"/>

            <!-- personInfo信息 -->
            <item-map name="info" desc="扩展信息" put-all="true">
                <item name="zipcode" desc="邮编"/>
                <item name="homeProvince" desc="籍贯省份"/>
                <item name="homeProvinceName" desc="籍贯省份" mapper="CODE_HASH" target="homeProvince"/>
                <item name="homeCity" desc="籍贯城市"/>
                <item name="homeCityName" desc="籍贯城市" mapper="CODE_HASH" target="homeCity"/>
                <item name="homeCounty" desc="籍贯县"/>
                <item name="homeCountyName" desc="籍贯县" mapper="CODE_HASH" target="homeCounty"/>
                <item name="address" desc="家庭住址"/>
                <item name="joinPartyDate" desc="入党日期"/>
                <item name="imeiNo" desc="IMEI号码"/>
                <item name="imsiNo" desc="IMSI号码"/>
                <item name="political" desc="政治面貌" />
                <item name="politicalName" desc="政治面貌" target="political" mapper="CODE_HASH" />
                <item name="education" desc="学历" notes="TYPE=10006"/>
                <item name="educationName" desc="学历" mapper="CODE_HASH" target="education"/>
                <item name="degree" desc="学位"/>
                <item name="degreeName" desc="学位" mapper="CODE_HASH" target="degree"/>
                <item name="graduateTime" desc="毕业时间"/>
                <item name="graduateSchool" desc="毕业院校"/>
                <item name="major" desc="专业"/>
                <item name="beginWorkTime" desc="参加工作时间"/>
                <item name="workTime" desc="入职时间"/>
                <item name="resignationTime" desc="离职时间"/>
                <item name="resignationReason" desc="离职原因"/>
            </item-map>


            <!-- 其他信息 -->
            <item name="userId" desc="userId" type="Integer"/>
            <item name="account" desc="人员账号"/>
            <item name="accountStatus" desc="账号状态 1-正常 2-冻结(锁定) 3-注销" type="Integer"/>
            <item name="roleNames" desc="批量角色名称" target="roleIds" mapper="ROLE_HASH"/>
            <item name="deptNames" desc="人员所在部门名称" target="deptIds" mapper="ORG_HASH"/>

            <!-- 头像 -->
            <item-map name="personImg" desc="人员头像json字符串信息">
                <item name="fileSize" desc="文件大小" />
                <item name="filePath" desc="文件路径"/>
                <item name="fileName" desc="文件名称"/>
                <item name="fileType" desc="扩展名"/>
            </item-map>
            <!-- 人员部门信息 -->
            <item-list name="ucenterPersonOrgs" desc="人员部门信息">
                <item name="deptId" desc="部门id" type="Integer"/>
                <item name="isMain" desc="主要部门" notes="1-是 0-否"/>
                <item name="isMainPerson" desc="主要负责人" notes="1-是 0-否"/>
                <item name="posId" desc="职位" type="Integer" />
                <item name="posName" desc="职位" target="posId" mapper="POS_HASH" />
                <item name="posLevel" desc="职级" notes="TYPE=10001-10080"/>
                <item name="posLevelName" desc="职级" notes="TYPE=10001-10080" target="posLevel" mapper="CODE_HASH"/>
            </item-list>
        </item-list>
    </rcv>
</trans>

=== github-big-cheng/dev-framework/user_center/ucenter/ucenter_web/src/main/resources/converter/ucenterlog/list.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="ucenterlog/list" desc="登录日志" group="登录日志" groupCode="ucenterlog">
    <send>
        <!--这里存放的是参数,之后补充完善-->
        <item name="pageNo" desc="页码" type="Integer" default="1"/>
        <item name="pageSize" desc="页容量" type="Integer" default="15"/>
        <item name="type" desc="操作类型" scope="10078-10,10078-20"/>
        <item name="timeQueryGe" desc="开始时间"/>
        <item name="timeQueryLe" desc="结束时间"/>
        <item name="accountQueryLike" desc="操作人员账号"/>
    </send>
    <rcv>
        <item name="total" type="Integer" desc="id" default="0"/>
        <item-list name="list" desc="">
            <item name="id" desc="id" type="Integer"/>
            <item name="orgId" desc="公司id" type="Integer"/>
            <item name="orgName" desc="公司名称"/>
            <item name="time" desc="操作时间" />
            <item name="type" desc="操作类型" />
            <item name="typeName" desc="操作类型" target="type" mapper="CODE_HASH" />
            <item name="ip" desc="ip地址"/>
            <item name="opContent" desc="事件内容"/>
            <item name="ipName" desc="表单签名打印规则名称" mapper="CODE_HASH" target="ip"/>
            <item name="machineName" desc="计算机名"/>
            <item name="userId" type="Integer" desc="用户ID T_UCENTER_USER"/>
            <item name="opState" type="Integer" desc="操作状态"/>
            <item name="createBy" type="Integer" desc="创建人 T_UCENTER_USER"/>
            <item name="createByValue" desc="创建人姓名" mapper="USER_PERSON_NAME_HASH" target="updateBy" />
            <item name="createTime" desc="创建时间 "/>
            <item name="updateBy" type="Integer" desc="修改人"/>
            <item name="updateByValue" desc="修改人姓名" mapper="USER_PERSON_NAME_HASH" target="updateBy"/>
            <item name="updateTime" desc="修改时间 "/>
        </item-list>
    </rcv>
</trans>

=== github-big-cheng/dev-framework/user_center/ucenter/ucenter_web/src/main/resources/converter/person/combox.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="person/combox" desc="人员信息-下拉列表" groupCode="person" group="人员管理">
    <send>
        <item name="sex" desc="性别" notes="TYPE=10001-10004"/>
        <item name="marriage" desc="婚姻状况" notes="TYPE=10001-10005"/>
        <item name="education" desc="学历状况" notes="TYPE=10001-10006"/>
        <item name="roleIdQuery" desc="角色id精确查询" type="Integer"/>
        <item name="nameQueryLike" desc="姓名模糊查询"/>
        <item name="nameOrAccountQueryLike" desc="姓名或者账号模糊查询"/>
        <item name="pathIds" desc="路径精确查询"/>
    </send>
    <rcv>
        <item-list ignore-key="true" desc="list" name="list">
            <!-- 基本信息 -->
            <item name="id" desc="人员id" type="Integer"/>
            <item name="orgId" desc="机构ID" type="Integer"/>
            <item name="orgName" desc="机构名称"/>
            <item name="name" desc="姓名"/>
            <item name="jobNo" desc="工号"/>
            <item name="idNo" desc="身份证号码"/>
            <item name="mobile" desc="手机"/>
            <item name="personState" desc="员工状态"/>

            <!-- 基本信息 -->
            <item name="sex" desc="性别 TYPE=10001-10004, 10004-10:男 10004-20:女 "/>
            <item name="sexName" desc="性别" mapper="CODE_HASH" target="sex"/>
            <item name="marriage" desc="婚姻状况 TYPE=10001-10005, 10005-10:已婚  10005-20:未婚 "/>
            <item name="marriageName" desc="婚姻状况" mapper="CODE_HASH" target="marriage"/>
            <item name="birthday" desc="出生日期"/>
            <item name="nation" desc="民族"/>
            <item name="nationName" desc="民族" target="nation" mapper="CODE_HASH"/>
            <item name="telephone" desc="电话"/>
            <item name="email" desc="email地址"/>
            <item name="memo" desc="备注"/>


            <item name="userId" desc="userId" type="Integer"/>
            <item name="account" desc="人员账号"/>
            <item name="accountStatus" desc="账号状态 1-正常 2-冻结(锁定) 3-注销" type="Integer"/>

            <!-- personInfo信息 -->
            <item-map name="info" desc="扩展信息" put-all="true">
                <item name="imeiNo" desc="IMEI号码"/>
                <item name="imsiNo" desc="IMSI号码"/>
                <item name="zipcode" desc="邮编"/>
                <item name="homeProvince" desc="籍贯省份"/>
                <item name="homeProvinceName" desc="籍贯省份" mapper="CODE_HASH" target="homeProvince"/>
                <item name="homeCity" desc="籍贯城市"/>
                <item name="homeCityName" desc="籍贯城市" mapper="CODE_HASH" target="homeCity"/>
                <item name="homeCounty" desc="籍贯县"/>
                <item name="homeCountyName" desc="籍贯县" mapper="CODE_HASH" target="homeCounty"/>
                <item name="address" desc="家庭住址"/>
                <item name="joinPartyDate" desc="入党日期"/>
                <item name="political" desc="政治面貌"/>
                <item name="politicalName" desc="政治面貌" target="political" mapper="CODE_HASH"/>
                <item name="education" desc="学历" notes="TYPE=10006"/>
                <item name="educationName" desc="学历" mapper="CODE_HASH" target="education"/>
                <item name="degree" desc="学位"/>
                <item name="degreeName" desc="学位" mapper="CODE_HASH" target="degree"/>
                <item name="graduateTime" desc="毕业时间"/>
                <item name="graduateSchool" desc="毕业院校"/>
                <item name="major" desc="专业"/>
                <item name="beginWorkTime" desc="参加工作时间"/>
                <item name="workTime" desc="入职时间"/>
                <item name="resignationTime" desc="离职时间"/>
                <item name="resignationReason" desc="离职原因"/>
            </item-map>
        </item-list>
    </rcv>
</trans>

=== github-big-cheng/dev-framework/user_center/ucenter/ucenter_web/src/main/resources/converter/org/add.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="org/add" desc="新增" group="部门管理" groupCode="org">
    <send>
        <!-- 基础信息 ucenterOrg -->
        <item name="code" desc="代码" required="true"/>
        <item name="cname" desc="中文名称" required="true"/>
        <item name="compType" desc="类型" required="true"
              notes="TYPE=10001-10027 10027-10:部门,10027-20:公司"/>
        <item name="pathIds" desc="路径" notes="ROOT_ID-10001-10002…"/>
        <item name="pathNames" desc="路径名称" notes="ROOT_ID-10001-10002…"/>
        <item name="ename" desc="英文名称"/>
        <item name="sname" desc="简称"/>
        <item name="linker" desc="企业/部门联系人"/>
        <item name="linkId" desc="联系人id" type="Integer"/>
        <item name="linkerMobilePhone" desc="联系人手机号"/>
        <item name="telephone" desc="办公电话"/>
        <item name="parentId" desc="上级部门ID" type="Integer"/>
        <item name="orderNo" desc="顺序号" type="Integer"/>
        <item name="memo" desc="备注"/>

        <!--详细信息 ucenterOrgInfo-->
        <item-map name="info" desc="info" put-all="true">

        </item-map>
    </send>
    <rcv>
        <item name="id" desc="id" type="Integer" ignore-key="true"/>
    </rcv>
</trans>

=== github-big-cheng/dev-framework/user_center/sys/sys_web/src/main/resources/converter/sysoperationlog/add.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="sysOperationLog/add" desc="新增" group="操作日志" groupCode="sysOperationLog">
    <send>
        <item name="className" desc="类名"/>
        <item name="columnName" desc="字段名"/>
        <item name="oldValue" desc="修改后"/>
        <item name="newValue" desc="修改后"/>
        <item name="billNo" desc="业务单号"/>
        <item name="bizId" desc="业务ID"/>
        <item name="userId" desc="用户ID"/>
        <item name="account" desc="账号"/>
        <item name="ip" desc="ip"/>
        <item name="machineName" desc="机器名称"/>
        <item name="time" desc="操作时间"/>
    </send>
    <rcv>
        <item name="id" desc="id" type="Integer" ignore-key="true"/>
    </rcv>
</trans>

=== github-big-cheng/dev-framework/user_center/ucenter/ucenter_web/src/main/resources/converter/person/edit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trans SYSTEM "converter.dtd">
<trans name="person/edit" desc="人员信息-修改" groupCode="person" group="人员管理">
    <send>
        <item name="id" desc="人员id" type="Integer" required="true"/>
        <item name="name" desc="姓名" required="true"/>
        <item name="account" desc="人员账号"/>

        <item name="jobNo" desc="代码"/>
        <item name="idNo" desc="身份证号码"/>
        <item name="mobile" desc="手机"/>

        <item name="sex" desc="性别" scope="10004-10,10004-20"
              notes="10004-10:男 10004-20:女"/>
        <item name="marriage" desc="婚姻状况" scope="10005-10,10005-20"
              notes="TYPE=10001-10005,10005-10:已婚 10005-20:未婚"/>
        <item name="birthday" desc="出生日期"/>
        <item name="nation" desc="民族"/>
        <item name="telephone" desc="电话"/>
        <item name="email" desc="email"/>
        <item name="memo" desc="备注"/>

        <item-map name="info" desc="人员信息">
            <item name="zipcode" desc="邮编"/>
            <item name="homeProvince" desc="籍贯省份" notes="TYPE=10001-10033"/>
            <item name="homeCity" desc="籍贯城市" notes="TYPE=10001-10034"/>
            <item name="homeCounty" desc="籍贯县" notes="TYPE=10001-10035"/>
            <item name="address" desc="家庭住址"/>
            <item name="political" desc="政治面貌"/>
            <item name="joinPartyDate" desc="入党日期"/>
            <item name="imeiNo" desc="IMEI号码"/>
            <item name="imsiNo" desc="IMSI号码"/>
            <item name="education" desc="学历" notes="TYPE=10001-10006"/>
            <item name="degree" desc="学位"/>
            <item name="graduateTime" desc="毕业时间"/>
            <item name="graduateSchool" desc="毕业院校"/>
            <item name="major" desc="专业"/>
            <item name="beginWorkTime" desc="参加工作时间"/>
            <item name="workTime" desc="入职时间"/>
            <item name="resignationTime" desc="离职时间"/>
            <item name="resignationReason" desc="离职原因"/>
        </item-map>

        <item name="roleIds" desc="角色ids"/>
        <item-json name="personImg" desc="人员头像json串" real-type="Map">
            <item name="fileSize" desc="文件大小" type="Integer"/>
            <item name="filePath" desc="文件路径"/>
            <item name="fileName" desc="文件名称"/>
            <item name="fileType" desc="文件类型"/>
        </item-json>

        <item-json name="ucenterPersonOrgs" desc="用户部门信息json串" real-type="List">
            <item name="deptId" desc="部门ID" required="true" type="Integer"/>
            <item name="isMain" desc="是否主部门" scope="0,1" type="Integer"/>
            <item name="isMainPerson" desc="是否主要人员" scope="0,1" type="Integer"/>
            <item name="posId" desc="职位" type="Integer"/>
            <item name="posLevel" desc="职级" notes="TYPE=10001-10080"/>
        </item-json>
    </send>
    <rcv>
        <item name="id" desc="id" type="Integer" ignore-key="true"/>
    </rcv>
</trans>
